### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ivanperez-keera** [walseb/The_Bearriver_Arcade#1]
Hi,

I've been going through the code, just to look around :)

This is really nice :) Congratulations! It should definitely be in the dunai and Yampa readmes.

I understand that these are just prototypes, but they are actually fun to play. With very minor changes, they could be something I could see myself having fun with. Some ideas:
- Lunar lander: let players know if they won or lost.
- SimpleGame1: further levels, longer level. It would be interesting to see that the game does have a time leak (if older blocks that you leave on the left remain in the world / in memory) -- I had this when I wrote a clone of flappy bird.
- SimpleGame2: this is a great idea for a game. I can't clear that square you have in the screenshot well :)

If you are serious about trying to make any of these into a bigger game, I'd suggest trying to simplify it as much as possible: trust me, it'll get really complex if you add all the features a game needs.

Minor suggestions specifically about the code:

- FRPEngine

Should Physics and Collision live under the same namespace?

- YampaUtils

I normally call this FRP.Yampa.Extra (or FRP.Yampa.Utils). It makes it easy to ignore.

https://github.com/walseb/The_Bearriver_Arcade/blob/02feca0416b666309180932315d4b84063b0c0b1/FRPEngine/src/FRPEngine/Collision/GJK.hs#L20-L23

Why not `fromMaybe False`?

https://github.com/walseb/The_Bearriver_Arcade/blob/master/FRPEngine/src/FRPEngine/Collision/GJK.hs#L15-L24

Why not:
```(fromMaybe False . collides) <$> (getCollisionPointsPos a) <*> (getCollisionPointsPos b)```

https://github.com/walseb/FRPSimpleGame2/blob/2eb7e7cbeed13b5b04f85dc9e11c02f35442abc9/src/Render/SDL/Render.hs#L16-L18

Why not:
`when alive $ renderSpr (player ^. (collObj . obj))`

https://github.com/walseb/The_Bearriver_Arcade/blob/master/FRPEngine/src/FRPEngine/Init.hs#L103-L110

Probably simplifiable with `IfElse`.

https://github.com/walseb/The_Bearriver_Arcade/blob/master/FRPEngine/src/FRPEngine/Init.hs#L113-L115

Why not: `min dt frameMaxJump`

https://github.com/walseb/FRPLunarLander/blob/09f033cab039d13710f8c69b6acfd66d2a120f22/src/Actors/Player.hs#L39-L43

Use `maybe`?

(I could go on for ages, cleaning code is my thing.)

**Comment by walseb** [comment]
Wow thanks a lot for looking through it!

Yeah my goal is to eventually create a real game, I made these just to not get into the same pitfalls I did in my previous attempt in F# where things got too complex too fast. I'm still learning a lot about haskell especially in regards to arrows so thanks a lot for your comments!

Maybe this should be an issue on the dunai page, but currently the largest roadblock I can see and the issue I have thought most about is integrating stateful (in the sense that they keep state) IO heavy applications such as physics engines into a pure FRP network, where the FRP network can add force to objects, respond to events, etc. I have heard about pretty neat theories of how to do it online, but do you know of anyone who has actually done this and written about it? I have avoided that issue so far by using simple pure collision detection and integrals to fake physics but when I get closer to making a proper game, a traditional physics engine such as bullet is probably necessary.

Besides that problem everything is looking great. I'm very excited to get [fir](https://gitlab.com/sheaf/fir) working so that I don't have to write shaders in GLSL when I attempt 3D. And performance isn't a problem yet at least. Oh and the levels are very hard because I had to play them so much while figuring everything out hah!

**Comment by walseb** [comment]
Oh and yeah, none of the games here do any kind of dynamic level loading or clean up parts of the level you have passed, in fact I suspect the whole level is rendered always, every frame even if it's off-screen. Unless SDL does view frustum culling automatically ofcourse.
