### ISSUE TITLE
Suggestion: use ghcWithPackages instead of ghc in shell.nix

### ISSUE THREAD

**Issue by Thra11** [walseb/The_Bearriver_Arcade#2]
At the moment:
```
❯ cd FRPSimpleGame2
❯ nix-shell --run "cabal run"
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.RemoteRepo {remoteRepoName = "hackage.haskell.org",
remoteRepoURI = http://hackage.haskell.org/, remoteRepoSecure = Just True,
remoteRepoRootKeys =
["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: FRPEngine-0.2.0.0 (user goal)
[__1] unknown package: vector (dependency of FRPEngine)
[__1] fail (backjumping, conflict set: FRPEngine, vector)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: FRPEngine, vector

```
If `FRPSimpleGame2/shell.nix` were modified to look something like this:
```
{ pkgs ? import <nixpkgs> { } }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    pkg-config
    cabal-install
    (haskellPackages.ghcWithPackages (hpkgs:
    with hpkgs; [
      vector
      sdl2-ttf
      sdl2-image
      gjk
      extra
      bearriver
      aeson
    ]))
    SDL2
    SDL2_image
    SDL2_ttf
  ];
}
```
Then `nix-shell --run "cabal run"` works out of the box.

I've only looked at FRPSimpleGame2 so far, but I expect the others would benefit from a similar/identical change.

**Comment by walseb** [comment]
Hi! Sorry for the late reply. 
That's strange, you shouldn't need to download any haskell packages through nix, cabal should take care of it all.
I tried that exact comand just now on the latest commit on this project in the `FRPSimpleGame2` folder and it worked fine. Although I see now that there are a few unused dependencies within these projects like `tiled`

**Comment by walseb** [comment]
Ah I see what's happening, you haven't run `cabal update` yet. Maybe there is a way to ensure this in nix, although I wouldn't want everyone trying out this package to be tricked into updating their hackage package list as it takes forever to rebuild all the packages if even just one far down dependency has been updated since their last update

**Comment by Thra11** [comment]
That's the benefit of using ghcWithPackages: It doesn't assume that cabal update's been run, nor does it require it. It will leave the user's system untouched, and it will fetch all the haskell dependencies from the nix binary cache, so it cuts down compile time.

**Comment by walseb** [comment]
That's true, but my experiences using nixpkgs for haskell packages hasn't been very good. They only keep the latest version of every haskell package (iirc) which often causes dependencies with many dependencies to not compile because they rely on some old version of some package. Although this packages dependencies might have their dependencies bound to the latest version right now, I fear some package this package relies on will forget to up it's versions causing the shell.nix to crash. I think the best way to do this would have been to use haskell.nix, but it's a bit too much effort for me to want to update this repo with it just now, especially given how messy some of these games are hah.

**Comment by Thra11** [comment]
Yeah, I guess the only way to ensure it would be reproducible would be to pin nixpkgs to a version that is known to have suitable versions of the haskell dependencies and no build failures instead of using the system nixpkgs. Ah well, it was just a suggestion. Thanks for taking the time to consider it!

**Comment by walseb** [comment]
Also a downside of pinning nixpkgs is that I'm pretty sure they delete their cache after a while so you would loose any speed benefits over cabal eventually. Thanks for your suggestion! And thanks for checking out these projects despite them not being the prime examples of bearriver usage. In particular I have given up on the pseudo hot-swapping this package attempts by outputting a valid save state every tick since it's very verbose. Also input management shouldn't be using dynamic arrays and a few other things. I haven't bothered fixing them but I hope to overhaul these to be examples in the "engine" I'm working on. Compared to the one present here it's really just going to be simplified input management and maybe a bunch of helper functions and wrappers around gpipe instead of SDL
